upstream processing {
    server processing-1:8082 max_fails=2 fail_timeout=5s;
    server processing-2:8082 max_fails=2 fail_timeout=5s;
    server processing-3:8082 max_fails=2 fail_timeout=5s;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://processing;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://dashboard:80;
        proxy_set_header Host $host;
    }
}
