spring:
  application:
    name: processing
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aegis}
    username: ${SPRING_DATASOURCE_USERNAME:aegis}
    password: ${SPRING_DATASOURCE_PASSWORD:aegis}
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8082

simulator:
  url: ${SIMULATOR_URL:http://localhost:8080}

broker:
  url: ${BROKER_URL:ws://localhost:8081}
