spring:
  application:
    name: processing
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/aegis}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082

simulator:
  url: ${SIMULATOR_URL:http://simulator:8080}

broker:
  url: ${BROKER_URL:ws://broker:8081}
